### ISSUE TITLE
DnsDumpster: list index out of range

### ISSUE THREAD

**Issue by geeknik** [gnebbia/pdlist#6]
## Expected Behavior
No error.

## Actual Behavior
```
[+]  Searching on Threatcrowd...
[+]  Searching on Hackertarget...
[+]  Searching on UrlScan...
[+]  Searching on DnsDumpster...
list index out of range
[+]  Searching on crt.sh...
[+]  Searching on certspotter...
[+]  Printing domain list
```

## Steps to Reproduce the Problem

  1. pdlist firefox.com -o /tmp/firefox.txt

## Specifications

  - Version:  Commit b7b449ef7c14553c17a287d4dda764d7c7f80f42
  - Platform: Ubuntu 18 LTS
  - Subsystem:  Python 3.7.3

**Comment by gnebbia** [comment]
It seems to be a problem related to dnsdumpster, indeed if you try from a python shell:
```
from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI
results = DNSDumpsterAPI().search("example.com")
```
you will get the same error, I can try to submit the issue to the dnsdumpster author.

**Comment by gnebbia** [comment]
Ok this has been solved with the new commits!
